### ISSUE TITLE
Extract classes and related meta info

### ISSUE THREAD

**Issue by clintgibler** [returntocorp/semgrepl#3]
(Just Python for now, but eventually should support all languages)

- [ ] extract every class
  - [x] Just class name
  - [ ] path
  - [ ] subclasses 
  - [ ] interfaces
  - [ ] annotations
  - [ ] instance vars, class vars
  - [ ] method definitions
